export const SET_TABLE_PAGINATION = 'SET_TABLE_PAGINATION';
export const SET_TABLE_FILTER = 'SET_TABLE_FILTER';
export const SET_TABLE_SORTER = 'SET_TABLE_SORTER';
export const SET_TABLE_TOTAL = 'SET_TABLE_TOTAL';
export const ADD_TABLE_EXPANDED_ROW = 'ADD_TABLE_EXPANDED_ROW';
export const SET_TABLE_EXPANDED_ROW = 'SET_TABLE_EXPANDED_ROW';