export const SET_TABLE_PARAMS = 'SET_TABLE_PARAMS';
export const SET_TABLE_PAGINATION = 'SET_TABLE_PAGINATION';
export const SET_TABLE_FILTER = 'SET_TABLE_FILTER';
export const SET_TABLE_SORTER = 'SET_TABLE_SORTER';
export const SET_TABLE_TOTAL = 'SET_TABLE_TOTAL';